### ISSUE TITLE
Division by 0 in GetAverage in Raster.cpp

### ISSUE THREAD

**Issue by deniscohen** [CoSci-LLC/KiLib-OSS#110]
For some unknown reason, the GetAverage function in Raster.cpp finds no candidate cells and thus divides by 0

**Comment by haydn-jones** [comment]
Two possibilities:

1. Each cell around the provided point is NODATA
2. The extent is so small that it loops over *no* cells.

We can fix this

**Comment by deniscohen** [comment]
> Two possibilities:
> 
> 1. Each cell around the provided point is NODATA
> 2. The extent is so small that it loops over _no_ cells.
> 
> We can fix this
> 
> [Link to GetAverage function](https://github.com/CoSci-LLC/KiLib-OSS/blob/8856bd25387524c461e0c415101b3e395072c756/KiLib/Raster/Raster.cpp#L181)

But shouldn't there be at least one point, the original point that should not be a no_data point?
I did a quick fix by making num = 1 if num =0.
But I am worried that something is not right.

**Comment by deniscohen** [comment]
Fixed in 704a99a
