### ISSUE TITLE
Enable certain optimization for Statslib

### ISSUE THREAD

**Issue by ohunter** [CoSci-LLC/KiLib-OSS#12]
Such as:
* `#define STATS_ENABLE_STDVEC_WRAPPERS`
* `#define STATS_USE_OPENMP`

**Comment by oparkins** [comment]
@haydn-jones 

I have verified that they are being added to the compilation inside the library: 
```
-DSTATS_ENABLE_STDVEC_WRAPPERS
```

I did not add the `STATS_USE_OPENMP` because PRIMULA would not build. But according to the docs:
> OpenMP functionality is enabled by default if the _OPENMP macro is detected (e.g., by invoking -fopenmp with GCC or Clang).

So instead I have just added `-fopenmp` to the cmake build. That should be enough to enable it.
