### ISSUE TITLE
Investigate whether or not KiLib is using FetchContent optimally

### ISSUE THREAD

**Issue by haydn-jones** [CoSci-LLC/KiLib-OSS#30]
In PRIMULA we are now doing this to pull in KiLib:
```CMake
### KiLib Install Process
include(FetchContent)

FetchContent_Declare(
	kilib_proj
	QUIET
	GIT_REPOSITORY git@github.com:CoSci-LLC/KiLib-OSS.git
	GIT_TAG        v2.4.2
	SOURCE_DIR     ${CMAKE_SOURCE_DIR}/lib/KiLib      # path within in the build directory.
)

FetchContent_GetProperties(kilib_proj)
if(NOT kilib_proj_POPULATED)
  FetchContent_Populate(kilib_proj)
  add_subdirectory(${kilib_proj_SOURCE_DIR} ${CMAKE_SOURCE_DIR}/lib/KiLib/build)
endif()
```

My suspicion is that what's happening now in KiLib with its libs is that they are being cloned on configure even if they are cached (populated), configure time seemed to speed up when doing this with PRIMULA.

**Comment by oparkins** [comment]
- Conditionally populating the content would save a few seconds. It looks like it makes sure it populates only once instead of each time it is called like in the original.
- I'm worried about the `add_subdirectory` being conditional though. We will have to test that to enough.
- Originally it was requested to move the path outside of the build directory... I prefer it to be inside the build directory, but I don't want to keep switching the location because we forget about the previous reason we moved it.

**Comment by oparkins** [comment]
https://cmake.org/cmake/help/latest/module/FetchContent.html

**Comment by haydn-jones** [comment]
What I was really hoping for was enabling PRIMULA to re-use the built version of KiLib / other libs in the `lib` folder when the build directory was cleared, because they really dont need to be recompiled again. Doesn't look like this helps with that. May just close this issue.

**Comment by oparkins** [comment]
I suspect we have to find a workflow that doesn't necessitate us deleting the build directory to solve that problem. Just building without wiping the build directory works pretty well for me. I just have to remember for any weird issue to wipe the directory.

**Comment by haydn-jones** [comment]
Closing out of fear of CMake

**Comment by oparkins** [comment]
@haydn-jones  I was thinking about this... 

What about two different options with CMake? By default, it will download a precompiled version of KiLib so there isn't any more compiling necessary. Option 2, is it will build it for you (used for debugging purposes)

**Comment by haydn-jones** [comment]
I do like that idea, would make compilation much faster.
