### ISSUE TITLE
User defined soils

### ISSUE THREAD

**Issue by deniscohen** [CoSci-LLC/KiLib-OSS#71]
I don't know if this option exists. If not this is going to be pretty critical for SOSlope2.
Parameters that the user can enter will be:
soil density, porosity, friction angle, cohesion, initial water content, van Genuchten parameters

Should we have/do we need a UserDefinedFactory like for Species?

**Comment by deniscohen** [comment]
We only need a subset of the soil properties, e.g., cohesion, friction angle, density, initial water content, porosity, van genuchten parameters (alpha and n)

**Comment by oparkins** [comment]
These `ValueDistribution` will just be a `constant` value for now.

**Comment by oparkins** [comment]
Look at CLI11 to parse the input files for soil descriptions. Still will need a Factory to build the soils dynamically.
