### ISSUE TITLE
Improve Interpolation code in Raster

### ISSUE THREAD

**Issue by haydn-jones** [CoSci-LLC/KiLib-OSS#77]
Interpolation code is long, ugly, and I believe slightly incorrect. Going to change that.

Note that a fix here will change the outputs of our packages that in some way shape or form utilize the interpolation in the Raster class.

Implement a matrix class that can be used in the raster and other packages. Should simplify the raster class and reduce bugs.

**Comment by deniscohen** [comment]
Done in Refactor branch
