### ISSUE TITLE
Add Armadillo to Cmake

### ISSUE THREAD

**Issue by oparkins** [CoSci-LLC/KiLib-OSS#83]
can you add Armadillo into the Issue80 branch on KiLib?

**Comment by oparkins** [comment]
@haydn-jones  It is added via CMake. Though it doesn't seem to be needed yet for it to build. I think all the other dependencies are handled properly.

When you add code that uses the library, let me know if it doesn't compile. Then I can "massage" cmake into working properly with the example code.

**Comment by deniscohen** [comment]
No longer needed
